### ISSUE TITLE
moveonenospc corrupted file in append mode

### ISSUE THREAD

**Issue by mnightingale** [trapexit/mergerfs#1180]
**Describe the bug**

`moveonenospc` behaviour resulting in corrupted file when file was opened in append mode and grew so that it has to be copied to a different branch.

This issue was originally reported at https://github.com/sabnzbd/sabnzbd/issues/2558 I investigated it and I'm fairly certain it's a mergerfs bug.

**To Reproduce**

This is simplified from the actual use case, but the intention is to use RAM as temporary storage and if more space is needed use slower disks.

Python3 POC script https://gist.github.com/mnightingale/6ee1fe797df09d340b62738868e66443

All this does is open a file in O_APPEND mode, write to it until it crosses the 200M limit so it needs to be moved to the other branch.

**Expected behaviour**

A 201MB file to exist at /home/mike/Downloads/tmp.dat
Instead I get a file twice the size with NUL bytes for the first ~200MB

**System information:**

 - OS, kernel version: `Linux mike-virtual-machine 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`
 - mergerfs version: `2.35.1`
 - mergerfs settings: 
tmpfs /mnt/ram tmpfs nodev,nosuid,noexec,nodiratime,size=200M 0 0
/mnt/ram:/home/mike/Downloads /mnt/pool fuse.mergerfs  defaults,noatime,allow_other,use_ino,cache.files=auto-full,dropcacheonclose=true,category.create=lfs,category.search=newest,moveonenospc=true,minfreespace=50M   0       0
 - List of drives, filesystems, & sizes:
   - `df -h`
tmpfs                        200M     0  200M   0% /mnt/ram
mnt/ram:home/mike/Downloads   39G   26G   12G  70% /mnt/pool
   - `lsblk -f`
 - A strace of the application having a problem:
   - `strace -fvTtt -s 256 -o /mnt/hgfs/ubuntu/mergerfspoc.strace.txt python3 mergerfspoc.py`
   https://gist.github.com/mnightingale/f3af90e839d47cba6d4c54bbda3d3cb7
 - strace of mergerfs while app tried to do it's thing:
   - `sudo strace -fvTtt -s 256 -p 5353 -o /mnt/hgfs/ubuntu/mergerfspoc-process.strace.txt python3 mergerfspoc.py`
   https://gist.github.com/mnightingale/58a0fd3a3f2632d23556384eb06fc269

**Additional context**

I'm no expert at the low level file system calls, but to me it looks like:

- it writes a load of data as expected until length is 209707008
- opens /home/mike/Downloads/tmp.dat.UPPOSE because it ran out of space
- ftruncate sets the length 209707008
- copy_file_range fails - because it was opened in O_APPEND mode
- falls back to a read/write copy from the old to new file but because of O_APPEND these go to the end of the file (~200MB + ~200MB)

I don't know what the best solution is; does it need a different code path for O_APPEND mode files such as open it first not in append mode for the copy_file_range and copydata_readwrite then reopen it after?

**Comment by trapexit** [comment]
Thanks for the report. I'll take a look but your description sounds likely. It's been a very long time since I touched that code but I don't recall trying to account specifically for O_APPEND. I might be reusing the file descriptor and probably shouldn't. I'll take a look this weekend.

**Comment by Crowley007** [comment]
Hi, have you had a chance to take a look? I had the original problem with sabnzbd & mergerfs and a smaller ram disk in the pool. Happy to test if there are any updates on this.

**Comment by trapexit** [comment]
Apologies, this slipped my mind. I'll have something for you to test this weekend.

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs/tree/append-move

Can you try this? I can build out a package if you need me to.

It did dawn on me while fixing this that there was talk of concurrent write support in FUSE a while back which could be a problem with this feature since I don't keep other writes from happening when this move is occurring. I'll need to look into this more. I'd rather not have to add a mutex to limit concurrent writes (if in fact supported) just for this but might need to.

**Comment by Crowley007** [comment]
Hi, yeah a package would help me test faster, I dont have a lot of experience compiling without a complete guide. I use Ubuntu LTS 22.04

**Comment by trapexit** [comment]
https://github.com/trapexit/mergerfs#debian--ubuntu

but Jammy deb attached

[mergerfs_2.35.1-5-gbe76b12~ubuntu-jammy_amd64.deb.zip](https://github.com/trapexit/mergerfs/files/11726281/mergerfs_2.35.1-5-gbe76b12.ubuntu-jammy_amd64.deb.zip)

**Comment by Crowley007** [comment]
Sorry, managed to miss that when quickly browsing the docs, probably could have managed. But thank you, I'll test and report back.

**Comment by Crowley007** [comment]
After a few tests, it does seem to work better than before, I don't think the files get corrupted anymore. But the direct unpack with sabnzbd still fails at the point when when the disk change happens, and every download needs to be repaired.  But now they can be repaired which was not the case before.

@mnightingale  any thoughts?

**Comment by Crowley007** [comment]
Files after the disk change can't be extracted without a "repair" for some reason. I think that before the repair failed and now it works, but I'm not sure anymore. The low level stuff goes over my head so I can't be much more help either.

**Comment by mnightingale** [comment]
Initially it looks like mergerfs is handling the append mode file as expected, the POC script wrote what I expected.

But downloads with [sabnzbd/sabnzbd](https://github.com/sabnzbd/sabnzbd) are sometimes missing chunks of data.

[4.0.2](https://github.com/sabnzbd/sabnzbd/tree/4.0.2) uses append mode and file was 266240 bytes short
[develop](https://github.com/sabnzbd/sabnzbd/tree/develop) branch we are switching to using seek and truncate, and it was missing a 266240 byte chunk.
The missing amount does vary, I've also seen a 593920 byte chunk missing.

I've not managed to reproduce it with strace running yet and probably won't get a chance until the weekend.

**Comment by trapexit** [comment]
OK. I'll see if I can reproduce it.

**Comment by Crowley007** [comment]
Thanks for looking into it guys.

**Comment by trapexit** [comment]
[mergerfs_2.35.1-5-g82430e1~ubuntu-jammy_amd64.deb.zip](https://github.com/trapexit/mergerfs/files/11730778/mergerfs_2.35.1-5-g82430e1.ubuntu-jammy_amd64.deb.zip)

**Comment by mnightingale** [comment]
The [Python write calls](https://docs.python.org/3/library/io.html?highlight=write#io.RawIOBase.write) now correctly report how much was written, which is more like I'd expect although it presents problems downstream.

Is it possible for mergerfs to handle writing the remainder after moving the file?

If not we could make sabnzbd handle it, but it's going to be a bit noisy code basically looping the write calls until there is nothing left.

**Comment by trapexit** [comment]
I'm sorry but I'm lost here and I'm not sure what you're asking. Why would it be a problem? What remainder? It gets an error, moves the file over, retries the write and things should continue as normal.

**Comment by mnightingale** [comment]
A quick POC https://gist.github.com/mnightingale/a005e4c27dd880e8fc36b2c0b950d756 on a 200M tmpfs

I'm giving it 716800 bytes to write on every call, but one of them (when it cross 200M) is only partially writing it.

```
$ python3 mergerfspoc.py 
At 209715200 wrote 409600 instead of 716800
```

Sounds like you expect it to retry?

**Comment by Crowley007** [comment]
Yeah just made a quick test, and unfortunately the issue still persists.

**Comment by trapexit** [comment]
I'm not sure yet why a short write would be happening. If I can avoid it I will. But yeah... not dealing with short reads/writes is corruption waiting to happen. I'll keep digging.

**Comment by mnightingale** [comment]
Snippet of an strace of mergerfs

```
410   19:49:18.852677 pwrite64(5, "5555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555"..., 716800, 209305600) = 409600 <0.000072>
410   19:49:18.852891 writev(4, [{iov_base="\30\0\0\0\0\0\0\0\272\23\0\0\0\0\0\0", iov_len=16}, {iov_base="\0@\6\0\0\0\0\0", iov_len=8}], 2) = 24 <0.000014>
410   19:49:18.853074 read(4,  <unfinished ...>
409   19:49:18.854328 <... read resumed>"D\0\0\0\26\0\0\0\274\23\0\0\0\0\0\0\30\0\0\0\0\0\0\0\350\3\0\0\350\3\0\0006\20\0\0\0\0\0\0\0\0\0\0\0\0\0\0security.capability\0", 1052672) = 68 <0.001659>
409   19:49:18.854495 newfstatat(AT_FDCWD, "/mnt/ram/tmp.dat", {st_dev=makedev(0, 0x25), st_ino=5, st_mode=S_IFREG|0664, st_nlink=1, st_uid=1000, st_gid=1000, st_blksize=4096, st_blocks=409600, st_size=209715200, st_atime=1686682158 /* 2023-06-13T19:49:18.206353706+0100 */, st_atime_nsec=206353706, st_mtime=1686682158 /* 2023-06-13T19:49:18.850352209+0100 */, st_mtime_nsec=850352209, st_ctime=1686682158 /* 2023-06-13T19:49:18.850352209+0100 */, st_ctime_nsec=850352209}, AT_SYMLINK_NOFOLLOW) = 0 <0.000036>
409   19:49:18.854765 newfstatat(AT_FDCWD, "/home/mike/Downloads/tmp.dat", 0x7f83c41f5280, AT_SYMLINK_NOFOLLOW) = -1 ENOENT (No such file or directory) <0.000026>
409   19:49:18.854952 lgetxattr("/mnt/ram/tmp.dat", "security.capability", NULL, 0) = -1 ENODATA (No data available) <0.000271>
409   19:49:18.855458 writev(4, [{iov_base="\20\0\0\0\303\377\377\377\274\23\0\0\0\0\0\0", iov_len=16}], 1) = 16 <0.000050>
410   19:49:18.855785 <... read resumed>"P\360\n\0\20\0\0\0\276\23\0\0\0\0\0\0\30\0\0\0\0\0\0\0\350\3\0\0\350\3\0\0006\20\0\0\0\0\0\0 +\20\264\203\177\0\0\0\0\200\f\0\0\0\0\0\360\n\0\0\0\0\0\0\0\0\0\0\0\0\0\1\204\0\0\0\0\0\00066666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666"..., 1052672) = 716880 <0.002533>
409   19:49:18.855900 read(4,  <unfinished ...>
410   19:49:18.856011 pwrite64(5, "6666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666"..., 716800, 209715200) = -1 ENOSPC (No space left on device) <0.000007>
```

So first pwrite64 writes 555... and is short the next pwrite64 is 666... and gets the ENOSPC which triggers a move_and_write.
I think the 555... should notice it was short, move the file and retry?

So is it as simple as this? no idea if there any repercussions?

```diff
diff --git a/src/fuse_write.cpp b/src/fuse_write.cpp
index 2be75ce..960aff3 100644
--- a/src/fuse_write.cpp
+++ b/src/fuse_write.cpp
@@ -97,7 +97,7 @@ namespace l
     fi = reinterpret_cast<FileInfo*>(ffi_->fh);
 
     rv = l::write(fi->fd,buf_,count_,offset_);
-    if(l::out_of_space(-rv))
+    if(l::out_of_space(-rv) || rv < count_)
       rv = l::move_and_write(buf_,count_,offset_,fi,rv);
 
     return rv;
```

I've tested this 10*1GB time into the 200MB branch and no issues.

**Comment by trapexit** [comment]
Why would it move on a short write? A short write is a totally valid situation. It can happen for multiple reasons. I shouldn't move a file just because I get a short write.

**Comment by trapexit** [comment]
This is where I was talking about earlier needing to double check FUSE behavior with O_APPEND. If the file is in append mode then retrying the write after may not be proper. With normal setup it's fine because it's a pwrite. I need to double check FUSE and syscall behavior.

**Comment by trapexit** [comment]
And unfortunately as I recall the append behavior may differ if using writeback caching. So there are a number of conditions to consider.

**Comment by mnightingale** [comment]
Right I think I understand, not a problem if you decide to leave it returning the short write, I'll just have to persuade sabnzbd to merge some retrying writes logic.

**Comment by trapexit** [comment]
I can't not at some point do a short return. I suppose I could try my own continuation (I don't think "retry" is appropriate as it is part of the API, it isn't an error, it may be uncommon but valid situation) to limit having to return back the short write return value but at the end of the day a short read and write are just valid things and it should be considered a bug not to handle them. I don't really want to be in the business of patching over other people's bugs if I can avoid it.

That said if I limit it to 1 attempt to write the yet written data it would cause mergerfs to notice the space error ever so slightly quicker but still the main thing is confirming how append works in the above mentioned situations. I have to write some tests.

**Comment by trapexit** [comment]
In testing different things I did find a bug with the moveonenospc feature when using writeback cache (with files opened with page caching) and technically in O_DIRECT writes (but since I don't support the latter at the moment it is theoretical.) It was what I had though... in those two cases the kernel can send parallel write requests. Problem is I don't do any sort of synchronization since in all other situation the kernel serializes requests. What that means is in this particular situation with writeback cache enabled + files opened with page caching (cache.files not equal 'off') then if a filesystem runs out of space numerous in flight requests could get that error and all try to move the file at the same time. 

There are a couple ways to manage this so I need to think about what may be the best method. Perhaps for now I can just add a mutex and serialize them. Otherwise I'd have to disable the feature if writeback cache is enabled.

This isn't going to be an issue for most and not you given your settings but still something I need to address.

**Comment by Crowley007** [comment]
Again, thanks to both of you for looking in to this!

**Comment by Crowley007** [comment]
And here is my fstab from the original issue on sab git: https://github.com/sabnzbd/sabnzbd/files/11442726/sabnzbd.log

**Comment by trapexit** [comment]
I'll have a new build for you to try soon. Debugging this opened a can of worms. Turned out I wasn't handling all situations correctly for the kernel and I will have to not return the short write to userspace anyway. At least when direct_io is not enabled. I've fixed it for when append is not enabled but due to a quirk with how Linux works with append mode and the pwrite call I have to do some more careful management of rewriting the failed data after moving the file.

**Comment by Crowley007** [comment]
I will be away from the Pc for a week, but will test if you have something ready when I get back.

**Comment by trapexit** [comment]
[mergerfs_2.35.1-7-ge64fbca~ubuntu-jammy_amd64.deb.zip](https://github.com/trapexit/mergerfs/files/11844308/mergerfs_2.35.1-7-ge64fbca.ubuntu-jammy_amd64.deb.zip)

**Comment by Crowley007** [comment]
Just did a few tests, and there were no errors. The issue seems to be fixed. Thank you! Will report back If the issue re-emerges.

**Comment by trapexit** [comment]
I figured it would so I already merged it. I'll be putting out a new release somewhat soon. Thanks for reporting this and helping debug. It's been this way for years. append isn't used much in my experience and just missed it. That and Linux treats append a little odd for certain syscalls which I hadn't realized. Otherwise it should have worked as it was.

**Comment by Crowley007** [comment]
A lot more testing later, unfortunately, it's still not completely fixed. My smaller tests finished fine, but with larger downloads I do get random disk write errors from sab, doesn't seem to be related to when the first pool disk gets full anymore though and doesn't always happen. The larger the download, the bigger the chance it errors out.. 

I do not get any errors if I don't use the mergerfs pool, so I guess it's still a variation on the same issue, but now the point at which it errors out is random, I tested this by using the same download over and over, it always failed at a different file and rarely there were no errors at all.

@mnightingale any idea what the problem could still be?

**Comment by trapexit** [comment]
That error is the most generic error there is and often a result of some code catching some more specific error and returning a generic one for some reason. 

Ideally a simple example could be created to replicate it or at least a strace.

**Comment by Crowley007** [comment]
Sorry that I can't be of more help, the filesystem stuff is beyond me. I hope @mnightingale has the time to take a look.

**Comment by trapexit** [comment]
Can you get me a trace? https://github.com/trapexit/mergerfs#support

The error suggests mergerfs is returning an error but I've seen software return filesystem errors themselves.

**Comment by Crowley007** [comment]
I tried to do a strace with the megerfs pid of the pool in question from the start of the download up to the point the error happens, but the file is 255MB. Even zipped it's 50MB and I can't upload it here.  Is this what you need? If so, where should I upload it?

**Comment by trapexit** [comment]
Don't have any cloud storage? gdrive? protondrive? mega.nz?

**Comment by Crowley007** [comment]
Google drive seems to work:

https://drive.google.com/file/d/1YL3oFhExtDKml47CnTUlgpEVclaD6HQ6/view

**Comment by trapexit** [comment]
Nothing looks out of the ordinary. But again... without the ability to replicate myself and see what the software is doing... :man_shrugging: 

Could someone point me to the software writing the file's code?

**Comment by Crowley007** [comment]
I can't help with the code, I hope @mnightingale can provide insight at some point.

I can try to describe what happens. Without mergerfs pool in the mix, sab downloads the rar files to a "Temporary Download Folder" while extracting at the same time to another folder. 

To get the best performance, this temp folder should be on SSD. I like to use RAM disk to reduce writes on the SSD, but since downloads can be bigger than the ram disk, I use mergerfs pool.  Right now 4GB ram disk and SSD for the rest.

Before, the files got corrupted when the first disk got full and mergerfs directed the writes to the second disk. With the latest test build, this isn't the case anymore, sab keeps  successfully  downloading to the second disk and extracting from there at the same time. So the corruption problem seems to be fixed.

But now, at some point, sab refuses to write the next rar file and gives the error above. This does not happen if I don't use mergerfs pool as a temp folder. 

With the current test download, I had it fail at the exact same rar file multiple times in a row. At this point the ram disk was full, at 4.4gb and the second disk had 7.2gb of files.  I then switched to a temp folder not on a pool to make sure, it finished fine. Then I switched the temp folder back to the pool, and now it finished fine too! 

So it's quite strange. When it fails to write, it seems to fail consistently. But some times it will not fail.  What I have observed though, is that files do get modified on the ram disk even after it gets full, probably working as intended but might be the cause?

**Comment by mnightingale** [comment]
@trapexit the software is https://github.com/sabnzbd/sabnzbd

I have managed to reproduce @Crowley007 issue, I haven't investigated further or tried with strace, perhaps this evening if I can.

It fails with error 5 at fout.write(data), so the file should exist.

However similarly I do notice that at the time of the failure there was little to no space left on the mount.

```
Filesystem                   Size  Used Avail Use% Mounted on
tmpfs                        200M  200M  8.0K 100% /mnt/ram
mnt/ram:home/mike/Downloads   98G   29G   66G  31% /mnt/pool
```

I'm testing with a zip of 20 copies of https://sabnzbd.org/tests/test_download_1000MB.nzb

@Crowley007 what release/branch of SAB are you using? I use the develop branch which doesn't use append mode.

**Comment by Crowley007** [comment]
I used the latest stable, 4.02 but when I ran in to this issue, I downloaded 4.0.3RC1 [[5a7abcb]. No change unfortunately.

**Comment by trapexit** [comment]
Is there some free usenet server I can use? I don't use usenet. I've never used this software. There is only so much I can do without a minimal reproducible example.

**Comment by Crowley007** [comment]
I can buy you 1 month of access if you want to test, or send you a 15$ etc. Whichever you prefer.

**Comment by trapexit** [comment]
There is no integration testing without using an existing service?

**Comment by Crowley007** [comment]
It looks like the sab test download files are indeed on the news servers. Perhaps @mnightingale can provide alternate means of testing like before, but if you want to try with usenet access, let me know.

**Comment by trapexit** [comment]
Not that I don't want to address this but can we step back and I better understand why using a small RAM disk? If it is running out of space regularly then I'm not seeing the value given it will hit the ENOSPC error and have to move it to another disk anyway. Even if it doesn't run out of space it will have to move it to a regular drive. Unless there is something funny with the software I would think it would be at best the same perf as without using it.

**Comment by Crowley007** [comment]
Because I had 8GB of ram on the server. In fact, I just put 32GB in there today, but the files I download from usenet vary from 1GB to 100GB. The main point is reducing unnecessary writes to the SSD and to put the "idle" ram to good use. The smaller downloads don't need to touch the SSD at all. Also, my SSD does not have a dram cache, so the performance does seem to be better also, but on this I can't be sure since my cable internet speed can fluctuate too. 

I used this setup for years with nzbget, but since it isn't updated anymore, I switched to sabnzbd and ran in to these issues.

**Comment by trapexit** [comment]
Sounds like something that the software could be improved to handle better but I see the possible advantages depending on how it works. Thanks.

I'll take a look at those servers. Thanks.

**Comment by Crowley007** [comment]
I suspect, and perhaps it was mentioned in these discussions, that nzbget works because it pre-allocates the files and sab doesn't. Not a huge deal if I need to go back to nzbget, but I have really  started to like sab and hope I can get this working.

Especially now with 32GB of ram, around 30Gb sit around doing nothing.

**Comment by trapexit** [comment]
It is unlikely it would 'sit around doing nothing.' The kernel is always caching files read and written (depending somewhat on some values set at the system and software level.) On my system with 32GB of RAM and 21GB of it is storing cached data.

Can also use zram to increase available virtual memory for these things.

**Comment by Crowley007** [comment]
For context, all of my software use at max 2GB of ram, and my OS and software take less than 3GB of disk space. Sure Linux will use the ram for cache, but this provides no concrete benefit for me, saving writes on the SSD do. With 8GB of ram, 5Gb ram disk worked perfectly with nzbget. I will now use maybe 28GB. And linux can still cache when the ram isn't needed for downloading.

**Comment by trapexit** [comment]
The only swap I use on my servers is zram based. I want apps to die rather than cause thrashing. zram for me has been a decent compromise. Unfortunately, it just hasn't been made as turnkey as I'd like to setup. I've been meaning to look into that at some point. As well as some sort of cache watcher / auto evicter.

**Comment by trapexit** [comment]
minfreespace is a filter for a policy. it won't "be respected" if the file being written goes beyond the limit. That's what moveonenospc is for.

https://github.com/trapexit/mergerfs#branches

/branch/path=MODE,MINFREESPACE

/ram=RW,1G

**Comment by trapexit** [comment]
@Crowley007 Can you share your mergerfs config?

**Comment by Crowley007** [comment]
Ok, I doubt minfreespace will help then. But I don't think any of the other settings affect this either, I've tried using many different options without any effect. Currently I test with this pool:

`/home/ilpo/download/incomplete/ram:/ssd /pool2 fuse.mergerfs  defaults,noatime,allow_other,use_ino,cache.files=partial,dropcacheonclose=true,category.create=ff,moveonenospc=true   0       0`

**Comment by trapexit** [comment]
I can't reproduce it with a 1GB file with cache.files enabled (not off). It happens with `off` and my guess is that it is a bug in sabnzbd but I've not caught it yet. If they aren't handling short writes as was suggested before it would explain it.

Setup is just 2 branches. First is a 1GB share (which is smaller than 1GB formatted naturally) and the second is much bigger. create policy = ff. It moves the file fine and md5sum is identical.

**Comment by Crowley007** [comment]
Yeah, it doesn'nt always fail, sometimes 100gb file finishes fine. Some times it fails after a few dozen gigs etc. I can try with cache on later.

But it seems to me it's just waiting to happen, the longer it downloads More likely it fails.

**Comment by trapexit** [comment]
The size of the file shouldn't matter terribly much as if you trigger the enospc move it always will happen at or below the size of the RAM branch. It behaves the same way every time. Gets error, copies data, continues. I can consistently break it by using cache.files=off because almost certainly sabnzbd is not properly handling short writes.

**Comment by Crowley007** [comment]
cache.files=partial|full|auto-full|per-process

I already have it on =partial, should I try full?

**Comment by trapexit** [comment]
partial, full, auto-full are all going to behave the same here. The differences are between page caching on and off. Not the type of on.

**Comment by Crowley007** [comment]
Ok, so it wont help because on =partial it does fail.

**Comment by trapexit** [comment]
All my basic tests pass and given are sequential I'm not sure where to look for issues. In the very least the fact that cache.files=off leads to constant corruption suggests a sabnzbd issue even if there is some other issue with mergerfs.

I'll try to confirm that by hard coding a short write into mergerfs and see if normal usage (not with moveonenospc) results in the same style of corruption.

**Comment by mnightingale** [comment]
I've not had any luck creating a reproducible example.

Certainly sabnzbd wont handle short writes but I did make a small patch for that when there was a chance it would be required, https://github.com/mnightingale/sabnzbd/tree/bugfix/assembly_retry_short_writes

But I don't think that's the problem, since we've both had write calls causing errno EIO

**Comment by trapexit** [comment]
In the traces provided mergerfs isn't returning EIO so I'm really not sure what to make of it. Do we have a trace of mergerfs and sabnzbd with the error being returned?

**Comment by Crowley007** [comment]
I can reproduce it almost every time, so I can try to take another strace.  I have no experience with it though,  so just to confirm is this command enough: `strace -fvTtt -s 256 -p <mergerfsPID-of-the-pool> -o /tmp/mergerfs.strace.txt`

**Comment by Crowley007** [comment]
https://drive.google.com/drive/folders/1UrGi1x_6O8Bzov0gzOmV2aqTHue4zDs5

The link contains to Straces using the command above and pid for the pool I use for the temp folder.

The larger one is the full download until the first error. The second starts from this errored paused state, and has 5 tries of resume each of which fail with "disk error".

**Comment by trapexit** [comment]
Nothing obvious in mergerfs. No errors are passed back. Either the kernel is returning an error outside mergerfs explicit triggering or the error isn't coming straight from the OS. Can you trace sabnzbd too? I need to see what request is returning the error.

**Comment by Crowley007** [comment]
I can try, but the app is a collection of python scripts, so I wonder if jus tracing the main script will work?

I guesss I'll try this:  `strace -fvTtt -s 256 -o /tmp/sab.strace.txt python3 SABnzbd.py`

**Comment by trapexit** [comment]
Yes, that's what `-f` does... follow forks / children. It should catch everything unless they do some special stuff.

**Comment by trapexit** [comment]
I'm seeing something odd but not sure why EIO would be returned. mergerfs is asked to write 2048 bytes. Then 765952. That totals 768000. The second request though results in an error of ENOSPC. Then it gets a request to write 768000 bytes to the same location that just failed and I think that is when the app gets EIO.

From sab's perspective it requested 768000 bytes and got 2048 back then tries to write 768000 again. Then that results in EIO. 

Seems to me the kernel split up the request for whatever reason and maybe the error returned isn't handled well and manifest as EIO by fuse for some reason. I don't know if fixing sab to correctly handle short writes will help but certainly couldn't hurt.

I'll see if I can write a custom app to try to replicate this behavior. Maybe there is some error handling logic that isn't quite right.

**Comment by Crowley007** [comment]
I did make one discovery, usually when the disk error happens, sab will pause and will not resume the download again. Except if you restart sab. Then it will continue like nothing happened.

**Comment by trapexit** [comment]
[mergerfs_2.35.1-11-g8329033~ubuntu-jammy_amd64.deb.zip](https://github.com/trapexit/mergerfs/files/11912652/mergerfs_2.35.1-11-g8329033.ubuntu-jammy_amd64.deb.zip)

Yup. I had messed up error handling but it would still should have errored I think. Just with a different error.

**Comment by Crowley007** [comment]
Several large test downloads later, no errors yet!

**Comment by Crowley007** [comment]
I have downloaded a lot today to test, no errors. I believe this is solved. If something should still come up, I will report here. Thanks again, to the both of you!

**Comment by trapexit** [comment]
What happens if you set cache.files=off?

**Comment by Crowley007** [comment]
I gave that a try, the real time "direct unpack" fails, and I saw a new error from sab "Corrupt rar file" once. I'm not seeing any downsides in my use case to keep the cache on though.

**Comment by trapexit** [comment]
Can you try it again with the short write patch?

**Comment by Crowley007** [comment]
I'll try that tomorrow

**Comment by Crowley007** [comment]
Few quick tests have finished without failure. @mnightingale are there plans to integrate this patch to master?

**Comment by trapexit** [comment]
The patch needs some work but minor.

**Comment by mnightingale** [comment]
Just to check I understand, cache.files=off can result in short writes and I complete agree applications should handle them regardless.

For @Crowley007 use is off or any on value better suited?

@trapexit thanks for your comments on my attempt at a patch, if required I’ll adapt and submit a PR. l’ll just need to persuade them that it’s required even though it seemingly hasn’t been an issue in the past.

**Comment by Crowley007** [comment]
I did not see any difference, speeds were good on both. Some fluctuation, but  it might just be my 1Gb cable internet which can fluctuate.

**Comment by trapexit** [comment]
> For @Crowley007 use is off or any on value better suited?

Perhaps ironically "direct_io" mode (ie cache.files=off) can often be faster due to bypassing the page cache. Think of it as a more direct, almost 1 to 1 from the client to mergerfs. In that mode it expects the server (mergerfs) to respond exactly. You ask to write 1024 bytes... it should return exactly how many bytes it wrote or error. The problem with me adding a "write n bytes" loop like most random software should do is that it could result in a mismatch of situations. If I short write, and the follow write is an error (like what happens in this case)... what do I return? I have to return an error because I've been asked not to return a short write but then the software is getting an incomplete picture. Granted the software could look the size up after the error if they care (and should) but it is not a great situation regardless. The main functional difference between the two modes is that `mmap` with shared pages won't work in direct_io mode since in the kernel it requires the page cache to work. 

There is some investigation into why the page cache is generally slower than direct io but that may take some time. If it was a simple situation of "X is better all the time" I'd just set the default to that and not discuss it so much in the docs but unfortunately it's not that simple.

> l’ll just need to persuade them that it’s required even though it seemingly hasn’t been an issue in the past.

I would hope it should need persuading. It's just a fact of the POSIX file IO API. It is a very common thing to miss and for normal files it typically isn't an issue but better to address it now than try to debug why some random corruption happens later. Imagine a situation like here with what mergerfs is doing but it could happen naturally. You write and get a short write because the filesystem is full. The software goes to write again and it succeeds because in the time between writes the filesystem has more free space because a file was removed... now the file is silently corrupted. If you need any help with the convincing feel free to tag me.

**Comment by trapexit** [comment]
Addressed in 2.36.0
