### ISSUE TITLE
readme incorrect re: fuse / fstab?

### ISSUE THREAD

**Issue by malventano** [trapexit/mergerfs#750]
OS: Ubuntu 20.04 LTS
From the readme:

> To have the pool mounted at boot or otherwise accessible from related tools use /etc/fstab.
> 
> # <file system>        <mount point>  <type>    <options>             <dump>  <pass>
> /mnt/disk*:/mnt/cdrom  /media/drives  mergerfs  allow_other,use_ino   0       0

After following this format, `mount -a` results in: `mount: (path): unknown filesystem type 'mergerfs'.`

After a bit more digging I realized it needs to be `fuse.mergerfs`, but this wasn't consistent with the example in the readme.

**Comment by trapexit** [comment]
What version do you have installed? Does `mount.mergerfs` exist?

**Comment by malventano** [comment]
Version: 2.28.1-1build1
mount.mergerfs appears to exist.

**Comment by fbuchmeier** [comment]
Hi,

I've also tested this with the Debian package provided from your release page (https://github.com/trapexit/mergerfs/releases/download/2.29.0/mergerfs_2.29.0.ubuntu-bionic_amd64.deb) with the following versions:

```
# mergerfs --version
mergerfs version: 2.29.0
FUSE library version: 2.9.7-mergerfs_2.29.0
fusermount version: 2.9.7-mergerfs_2.29.0
using FUSE kernel interface version 7.31
```

```
# uname -a
Linux beliar 4.15.0-106-generic #107-Ubuntu SMP Thu Jun 4 11:27:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-106-generic x86_64)
```

```
# mount -a
mount: /media/backup: unknown filesystem type 'mergerfs'.
# ln -s /usr/sbin/mount.mergerfs /sbin/mount.mergerfs
# mount -a
```

Mounting a filesystem by using `mergerfs` or `mount.mergerfs` is fine, mounting it via `/etc/fstab` only works after symlinking `/usr/sbin/mount.mergerfs` to `/sbin/mount.mergerfs`.

Regards,
Florian.

**Comment by trapexit** [comment]
It's been fixed in the master branch. The deb build behavior was overriding what was supposed to be installed.

**Comment by maxisme** [comment]
After following the Generic build steps I still have the same problem:
> unknown filesystem type '/usr/local/bin/mergerfs'.

tail of the build script:
```
install -D build/mergerfs-fusermount "/usr/local/bin/mergerfs-fusermount"
install -D build/mount.mergerfs "/usr/local/sbin/mount.mergerfs"
chown root:root "/usr/local/bin/mergerfs-fusermount"
chmod u+s "/usr/local/bin/mergerfs-fusermount"
make[1]: Leaving directory '/root/mergerfs/libfuse'
Makefile:178: "pandoc does not appear available: unable to build manpage"
mkdir -p "/usr/local/share/man/man1"
install -v -m 0644 "man/mergerfs.1" "/usr/local/share/man/man1/mergerfs.1"
'man/mergerfs.1' -> '/usr/local/share/man/man1/mergerfs.1'
```

**Comment by trapexit** [comment]
What is that error from?

If you want to use 'mergerfs' as the name of the filesystem you *have* to install mount.mergerfs into /sbin.

**Comment by maxisme** [comment]
From `mount -a`:
`/etc/fstab`:
```
/4TB:/4TB2:/1TB /HDDs mount.mergerfs  allow_other,use_ino   0       0
```

After running:
```
# dpkg -i mergerfs_2.29.0.ubuntu-bionic_amd64.deb 
# ln -s /usr/sbin/mount.mergerfs /sbin/mount.mergerfs
# mount -a
```

**Comment by trapexit** [comment]
The name of the filesystem is not "mount.mergerfs". It's "fuse.mergerfs" or if mount.mergerfs is properly installed and such just "mergerfs"

**Comment by trapexit** [comment]
#790
